### ISSUE TITLE
Loosen dependencies to work with nightly stackage.

### ISSUE THREAD

**Issue by GregorySchwartz** [choener/ForestStructures#1]
In the dependencies for BiobaseNewick-0.0.0.1:
    QuickCheck-2.9.2 must match >=2.7 && <2.9 (latest applicable is 2.8.2)
    aeson-1.0.2.1 must match >=0.8 && <0.11 (latest applicable is 0.10.0.0)
    base-4.9.0.0 must match >=4.7 && <4.9 (latest applicable is 4.8.2.0)
    binary-0.8.3.0 must match >=0.7 && <0.8 (latest applicable is 0.7.6.1)

**Comment by choener** [comment]
Sorry, that one went under the radar for far too long.
Done now.
